//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees2
    {
        public Employees2()
        {
            this.Distribution2 = new HashSet<Distribution2>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Distribution2> Distribution2 { get; set; }
    }
}
