//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class newRequest
    {
        public int Cid { get; set; }
        public int Restaurent_Id { get; set; }
        public string Food_Item { get; set; }
        public string Max_Preservation_Time { get; set; }
    
        public virtual Restaurent Restaurent { get; set; }
    }
}
